spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/employee
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
server:
  port: 8082
springdoc:
  swagger-ui:
    path: /v1/swagger/index.html
  api-docs:
    path: /v1/swagger/api-docs
